In [2]:
import pandas as pd
import numpy as np
a = np.arange(0,10)
b = 2*a
c = np.vstack((a,b))

In [4]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [9]:
d = c.transpose(1,0)

In [10]:
x = torch.r

array([[ 0,  0],
       [ 1,  2],
       [ 2,  4],
       [ 3,  6],
       [ 4,  8],
       [ 5, 10],
       [ 6, 12],
       [ 7, 14],
       [ 8, 16],
       [ 9, 18]])

In [24]:
d[1:3,-1]

array([2, 4])

In [3]:
import torch
import torch.nn as nn

In [8]:
rnn = nn.GRU(10, 20, 2)
input = torch.randn(3, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input, h0)

In [9]:
input

tensor([[[-6.1281e-01,  3.8670e-01,  2.3783e+00, -7.7360e-01,  6.0547e-01,
           6.7861e-01,  9.0533e-01, -8.9843e-01,  3.2128e-01,  2.8122e-01],
         [-1.8168e+00, -1.1571e-01, -2.7657e-01, -1.2343e-01,  7.6067e-01,
           1.4627e+00,  1.5787e-02,  3.5557e-01, -3.7995e-01,  5.6658e-01],
         [ 7.5823e-01,  3.2799e-01,  1.8378e+00, -3.4178e-01, -1.4154e-01,
          -9.4094e-01,  6.7306e-01,  7.7368e-01, -1.6525e+00, -1.8141e+00]],

        [[-1.2697e+00,  6.0902e-01,  1.7185e+00, -1.4652e-01,  1.1188e+00,
          -5.0829e-02, -5.7748e-01, -6.5127e-01, -3.4140e-02, -9.6552e-01],
         [-5.1246e-01, -5.9595e-01, -4.7315e-01, -3.2573e-01,  8.7564e-01,
           1.9171e-01, -5.5307e-01,  2.7747e-01,  5.9195e-01, -3.5599e-01],
         [ 3.9286e-01, -4.9144e-01, -1.1214e+00, -1.9325e-01, -1.8080e-02,
           1.7494e+00, -9.3707e-01, -3.9774e-01,  1.5232e+00,  1.3356e+00]],

        [[-9.5724e-01, -3.1597e-02,  4.2037e-01,  7.8466e-01,  5.6585e-01,
           1.61

In [11]:
k,q,v = input.chunk(3, dim=-1)

In [12]:
k

tensor([[[-6.1281e-01,  3.8670e-01,  2.3783e+00, -7.7360e-01],
         [-1.8168e+00, -1.1571e-01, -2.7657e-01, -1.2343e-01],
         [ 7.5823e-01,  3.2799e-01,  1.8378e+00, -3.4178e-01]],

        [[-1.2697e+00,  6.0902e-01,  1.7185e+00, -1.4652e-01],
         [-5.1246e-01, -5.9595e-01, -4.7315e-01, -3.2573e-01],
         [ 3.9286e-01, -4.9144e-01, -1.1214e+00, -1.9325e-01]],

        [[-9.5724e-01, -3.1597e-02,  4.2037e-01,  7.8466e-01],
         [ 5.5182e-01, -3.0776e+00,  8.4301e-01, -4.5864e-01],
         [ 2.3543e-01, -1.7057e+00, -2.6968e-04, -8.0781e-01]]])

In [1]:
input = torch.randn(3,10)
output, hn = rnn(input)

NameError: name 'torch' is not defined

In [11]:
output

tensor([[ 0.0700, -0.0464, -0.1224,  0.0541,  0.0140,  0.1319, -0.0883,  0.1962,
          0.1741,  0.1686, -0.0255, -0.0885, -0.0958,  0.0424, -0.1204,  0.1565,
         -0.0657,  0.0256, -0.0477,  0.0967],
        [ 0.1759,  0.0526, -0.1555,  0.0027,  0.0415,  0.1108, -0.0773,  0.2646,
          0.1366,  0.2083, -0.0532, -0.0339, -0.1614,  0.0007, -0.0927,  0.2881,
         -0.2409, -0.0099, -0.1941,  0.1489],
        [ 0.1751,  0.0665, -0.1542,  0.0096,  0.1375,  0.1545, -0.0436,  0.1569,
          0.0844,  0.2065, -0.0726,  0.0557, -0.2066, -0.0826, -0.0340,  0.2660,
         -0.1611, -0.0154, -0.1847,  0.1645]], grad_fn=<SqueezeBackward1>)

In [1]:
token = '19e8eec1bcb4772464561a9dfa2e2dd0eec9c3e89557852b31592287'
import tushare as ts

In [2]:
ts.set_token(token)
pro = ts.pro_api()

csi300 = pro.index_daily(ts_code='399300.SZ')

In [3]:
csi300

,ts_code,trade_date,close,open,high,low,pre_close,change,pct_chg,vol,amount
0,399300.SZ,20240315,3569.9930,3554.9068,3572.8091,3533.6798,3562.2229,7.7701,0.2181,1.383160e+08,2.439916e+08
1,399300.SZ,20240314,3562.2229,3571.7885,3597.4600,3545.6120,3572.3610,-10.1381,-0.2838,1.409627e+08,2.638036e+08
2,399300.SZ,20240313,3572.3610,3594.4211,3594.4211,3563.3685,3597.4939,-25.1329,-0.6986,1.445906e+08,2.668988e+08
3,399300.SZ,20240312,3597.4939,3592.5826,3605.6976,3574.2117,3589.2635,8.2304,0.2293,1.806856e+08,3.399970e+08
4,399300.SZ,20240311,3589.2635,3545.9427,3589.2635,3542.2789,3544.9099,44.3536,1.2512,1.482028e+08,2.864186e+08
...,...,...,...,...,...,...,...,...,...,...,...
4659,399300.SZ,20050110,993.8790,983.7600,993.9590,979.7890,983.9580,9.9210,1.0083,5.791698e+06,3.762933e+06
4660,399300.SZ,20050107,983.9580,983.0450,995.7110,979.8120,983.1740,0.7840,0.0797,7.298694e+06,4.737469e+06
4661,399300.SZ,20050106,983.1740,993.3310,993.7880,980.3300,992.5640,-9.3900,-0.9460,6.288029e+06,3.921015e+06
4662,399300.SZ,20050105,992.5640,981.5770,997.3230,979.8770,982.7940,9.7700,0.9941,7.119109e+06,4.529208e+06


In [6]:
x = torch.randn(2, 3)


In [14]:
torch.cat((x, x, x), -1)

tensor([[-0.0032,  0.6143, -0.2981, -0.0032,  0.6143, -0.2981, -0.0032,  0.6143,
         -0.2981],
        [-0.5227, -0.9649,  1.0499, -0.5227, -0.9649,  1.0499, -0.5227, -0.9649,
          1.0499]])

In [7]:
torch.transpose(x, 0, 1)

tensor([[-0.0032, -0.5227],
        [ 0.6143, -0.9649],
        [-0.2981,  1.0499]])

In [8]:
x.permute(1,0)

tensor([[-0.0032, -0.5227],
        [ 0.6143, -0.9649],
        [-0.2981,  1.0499]])

In [10]:
x.permute(1,0).transpose(0,1)

tensor([[-0.0032,  0.6143, -0.2981],
        [-0.5227, -0.9649,  1.0499]])