In [1]:
from datasets import load_dataset
import torch 
from torch.utils.data import DataLoader

In [2]:
colnames = ['date', "movement_percent", "open_price", "high_price", "lowprice", "close_price", "volume"]
dataset = load_dataset("csv", data_dir='/home/userroot/projs/xiaojiucai/stocknet_data/price/preprocessed', sep='\t', header = 0,  names = colnames)

Resolving data files:   0%|          | 0/88 [00:00<?, ?it/s]

In [3]:
loader = DataLoader(dataset=dataset['train'], batch_size=1)

In [4]:
import pandas as pd
colnames = ['date', "movement_percent", "open_price", "high_price", "lowprice", "close_price", "volume"]
df = pd.read_csv('/home/userroot/projs/xiaojiucai/stocknet_data/price/preprocessed/AAPL.txt',sep='\t',header=0, names=colnames, )


In [23]:
s = df[['open_price']]
s2 = df['open_price']

In [38]:
df_no_date = df.iloc[:,1:]
array = df_no_date.values

In [39]:
import torch
t1 = torch.tensor(array) 

In [42]:
t1.shape

torch.Size([1256, 6])

In [49]:
t2 = t1.permute(1,0)
t2.shape

torch.Size([6, 1256])

In [52]:
t3 = t2.unsqueeze(2)

In [53]:
t3.shape

torch.Size([6, 1256, 1])

In [55]:
t3[0,:,:]

tensor([[ 0.0040],
        [ 0.0027],
        [ 0.0089],
        ...,
        [ 0.0062],
        [ 0.0090],
        [-0.0070]], dtype=torch.float64)

In [56]:
colnames = ['date', "movement_percent", "open_price", "high_price", "lowprice", "close_price", "volume"]
stock_dataset = load_dataset("csv", data_dir='/home/userroot/projs/xiaojiucai/stocknet_data/price/preprocessed', sep='\t', header = 0,  names = colnames)

Resolving data files:   0%|          | 0/88 [00:00<?, ?it/s]

In [2]:
import os
import pandas as pd
from torchvision.io import read_image
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
import pathlib
from torchvision.transforms import v2

class StockDataset(Dataset):
    def __init__(self, csv_dir, transform=None, target_transform=None):
        self.stock_list = os.listdir(csv_dir)
        self.csv_dir = csv_dir
        self.transform = transform
        self.target_transform = target_transform

    def __len__(self):
        return len(self.stock_list)

    def __getitem__(self, idx):
        stock_price_path = os.path.join(self.csv_dir, self.stock_list[idx])
        stock_name = pathlib.Path(stock_price_path).stem
        colnames = ['date', "movement_percent", "open_price", "high_price", "lowprice", "close_price", "volume"]
        df = pd.read_csv(stock_price_path,sep='\t',header=0, names=colnames)
        prices = df.iloc[:,1:].values
        prices_t = torch.tensor(prices)
        prices_t = prices_t.permute(1,0).unsqueeze(2)
        prices_t = v2.Resize([1024,1])(prices_t)
        # if self.transform:
        #     image = self.transform(image)
        # if self.target_transform:
        #     label = self.target_transform(label)
        return prices_t, stock_name

In [3]:
dataset = StockDataset(csv_dir='/home/userroot/projs/xiaojiucai/stocknet_data/price/preprocessed'
             )

In [4]:
len(dataset)

88

In [5]:
from torch.utils.data import DataLoader
loader = DataLoader(dataset, batch_size=4, shuffle=True)

In [7]:
for prices, name in loader:
    print(prices)
    print(name)

tensor([[[[-6.8951e-03],
          [-6.8951e-03],
          [-6.8951e-03],
          ...,
          [-6.8951e-03],
          [-6.8951e-03],
          [-6.8951e-03]],

         [[ 2.5560e-03],
          [ 2.5560e-03],
          [ 2.5560e-03],
          ...,
          [ 2.5560e-03],
          [ 2.5560e-03],
          [ 2.5560e-03]],

         [[ 3.7018e-03],
          [ 3.7018e-03],
          [ 3.7018e-03],
          ...,
          [ 3.7018e-03],
          [ 3.7018e-03],
          [ 3.7018e-03]],

         [[-8.6934e-03],
          [-8.6934e-03],
          [-8.6934e-03],
          ...,
          [-8.6934e-03],
          [-8.6934e-03],
          [-8.6934e-03]],

         [[-4.4186e-01],
          [-4.4186e-01],
          [-4.4186e-01],
          ...,
          [-4.4186e-01],
          [-4.4186e-01],
          [-4.4186e-01]],

         [[ 7.1750e+06],
          [ 7.1750e+06],
          [ 7.1750e+06],
          ...,
          [ 7.1750e+06],
          [ 7.1750e+06],
          [ 7.1750e+06]]]

In [1]:
import torch
torch.tensor([10], dtype=torch.float)

tensor([10.])